version: '3.8'

services:
  backend:
    image: python:3.9
    container_name: backend
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    ports:
      - "5055:5055"
    networks:
      - webnet

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet: